version: "3"

volumes:
  postgres:

services:
  postgres:
    image: postgres:13
    tty: true
    restart: on-failure
    healthcheck:
      test: pg_isready -U exchange_rate_test_task -d exchange_rate_test_task
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_USER: exchange_rate_test_task
      POSTGRES_PASSWORD: exchange_rate_test_task
      POSTGRES_DB: exchange_rate_test_task
    volumes:
      - postgres:/var/lib/postgresql/data

  redis-master:
    image: 'bitnami/redis:latest'
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    depends_on:
      - redis-master
    environment:
      REDIS_MASTER_SET: "redis-master"
      REDIS_MASTER_HOST: "redis-master"

  app:
    image: ${DOCKER_REPOSITORY}/${APP_NAME}:${VERSION}
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - configs/env.example
    deploy:
      replicas: 1

  helper:
    image: ${DOCKER_REPOSITORY}/${APP_NAME}-helper:${VERSION}
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - configs/env.example
    volumes:
      - ./:/app